# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9f931df139d27afafcd9e9b31ca386565e7491833ae867f586b0cc83c1fe085b73607d35188fe7bdcaaf3a0df1c9fd95fffd9407c7634929b415f0d71fbd753

test:
  secret_key_base: 77ea732f97d670e105484bf4bbcc790775b04c8565a02327b35438928dbf3085926750586fce782f31c0aba48ea3d82b4469c111301b57da9df0cd86786516cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
